blog/urls.py
from django.conf.urls import url

from . import views



urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^blogs/$', views.BlogListView.as_view(), name='blogs'),
    url(r'^blog/(?P<pk>\d+)$', views.BlogDetailView.as_view(), name='blog_detail'),
    url(r'^blog/(?P<pk>\d+)/comment/$', views.BlogCommentCreate.as_view(), name='blog_comment'),
    url(r'^authors/$', views.AuthorsListView.as_view(), name='authors'),
    url(r'^authors/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author_detail'),


]

mozBlogProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),

]


#this is for auth
urlpatterns += [
    url('^accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

from datetime import date
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User  # Blog author or commenter


class BlogAuthor(models.Model):
    """
    Model representing a blogger.
    """
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Enter your bio details here.")

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog-author instance.
        """
        return reverse('blogs_by_author', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.user.username

class Blog(models.Model):
    """
    Model representing a blog post.
    """
    name = models.CharField(max_length=200)
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
    # Foreign Key used because Blog can only have one author/User, but bloggsers can have multiple blog posts.
    description = models.TextField(max_length=2000, help_text="Enter you blog text here.")
    post_date = models.DateField(default=date.today)

    class Meta:
        ordering = ["-post_date"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog_detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name


class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # Foreign Key used because BlogComment can only have one author/User, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title = 75
        if len(self.description) > len_title:
            titlestring = self.description[:len_title] + '...'
        else:
            titlestring = self.description
        return titlestring

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView

from .models import Blog, BlogAuthor, BlogComment

# Create your views here.
from django.views import generic


def index(request):
    """
    View function for home page of site.
    """
    # Render the HTML template index.html
    return render(
        request,
        'index.html',
    )

class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5
    template_name = ('/blog/blog_list')

class AuthorsListView(generic.ListView):
    model = BlogAuthor
    paginate_by = 5

class BlogDetailView(generic.DetailView):
    """
    Generic class-based detail view for a blog.
    """
    model = Blog

class AuthorDetailView(generic.DetailView):
    model = BlogAuthor

class BlogCommentCreate(CreateView):
    """
    creates a comment object
    """
    model = BlogComment #specify which model can be created here
    fields = ['description', ] # which fields can be openly editted

    def get_context_data(self, **kwargs):
        """
        attach parent blog so I can display it on the comment template
        :param kwargs:
        :return:
        """
        #refer to the super view to generate context base
        context = super(BlogCommentCreate,self).get_context_data(**kwargs)
        #set 'blog' to equal queryset of Blog objects matching pk
        context['blog'] = get_object_or_404(Blog, pk=self.kwargs['pk'])
        #this will return a blog object
        return context

    def form_valid(self, form):
        """
        add associate blog and author to form.
        """
        #this is setting the author of the form
        form.instance.author = self.request.user
        #associate comment with blog based on passed
        form.instance.blog = get_object_or_404(Blog, pk = self.kwargs['pk'])
        #the super class carried the validator function
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self):
        """
        After posting comment return to associated blog.
        """
        return reverse('blog_detail', kwargs={'pk': self.kwargs['pk'], })

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Django DIY Blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

<div class="row">
  <div class="col-sm-2">
  {% block sidebar %}
  <ul class="sidebar-nav">

    {% if user.is_authenticated %}
    <li><a href="{% url 'logout' %}">Logout</a></li>
    {% else %}
    <li><a href="{% url 'login' %}">Login</a></li>
    {% endif %}

    <li><a href="{% url 'blogs' %}">All Blogs</a></li>
    <li><a href="{% url 'authors' %}">All Bloggers</a></li>
  </ul>
  {% endblock %}
  </div>
  <div class="col-sm-10 ">

    {% block content %}{% endblock %}


  </div>
</div>


</body>

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block content %}

<h1> {{blog.name}} </h1>
<h3> In the wise words of {{ blog.author }}, </h3>
<h4> {{ blog.description }} </h4>


<a href="{% url 'blog_comment' blog.id %}">Add a fookin comment eh</a>

{% if blog.blogcomment_set.all %}

<ul>
{% for comment in blog.blogcomment_set.all %}
    <li>
        {{ comment.author }} says- "{{comment.description}}"
    </li>
{% endfor %}

</ul>


{% else %}
<h5> no comments </h5>
{% endif %}


{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block content %}

<h1> List of all available blogs </h1>

<ul>
{% for blog in blog_list %}
    <li>
        <a href=" {{ blog.get_absolute_url }} "> {{ blog.name }}  </a>
    </li>
    {% endfor %}

</ul>

{% endblock %}

blog/templates/blog/blogauthor_detail.html
{% extends 'base.html' %}

{% block content %}

<h1> {{blogauthor.user}} </h1>
<h5> It's his world out there</h5>

<p> The list of rambles </p>

{% if blogauthor.blog_set.all %}
    <ul>
    {% for blog in blogauthor.blog_set.all %}
        <li>

            <a href="{% url 'blog_detail' blog.pk %}"> {{ blog.name }} </a>

        </li>
    {% endfor %}
    </ul>



{% else %}
<p> No rambles...yet </p>
{% endif %}



{% endblock %}

blog/templates/blog/blogauthor_list.html
{% extends 'base.html' %}

{% block content %}


{% if blogauthor_list %}

<ul>
    {% for author in blogauthor_list %}

    <li><a href="{% url 'author_detail' author.pk %}"> {{ author.user }} </a></li>

    {% endfor %}

</ul>


{% endif %}

{% endblock %}

blog/templates/blog/blogcomment_form.html
{% extends 'base.html' %}

{% block content %}

<p>Post your comment for: <a href="{% url 'blog_detail' blog.pk %}">{{blog.name}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>


{% endblock %}

blog/templates/index.html
<h1>You fuck face</h1>